"""d_major_bossa_title_v6.mid  ->  4-bar intro + loop.
Writes  assets/d_major_bossa_title_v7_intro.mid  and  src/music_data.c
Run: python3 tools/make_music.py
"""
import struct, math, sys
sys.path.insert(0, 'tools')
from midiparse import parse

SRC = 'assets/d_major_bossa_title_v6.mid'
OUT_MID = 'assets/d_major_bossa_title_v7_intro.mid'
PPQ, BAR = 480, 1920
INTRO = 4 * BAR
LOOP = 8 * BAR
UNITS_PER_TICK = 262144.0 * 60.0 / 84.0 / 480.0       # timer units (F/64) per MIDI tick

fmt, div, tr = parse(SRC)
assert div == PPQ

def notes_of(ti):
    on, out = {}, []
    for t, k, st, d in tr[ti]:
        if k != 'ch': continue
        c = st >> 4
        if c == 9 and d[1] > 0: on[d[0]] = (t, d[1])
        elif c == 8 or c == 9:
            t0, v = on.pop(d[0]); out.append((t0, t - t0, d[0], v))
    return sorted(out)

lead, comp, bass, perc = (notes_of(i) for i in (1, 2, 3, 4))

# ---- 4-bar intro, built only from the song's own material -------------------------
# bar 1: bass + percussion            bar 2: + comp (chord arps)
# bar 3-4: + lead, playing the song's last two bars (ends on the same C#5 -> D turn-around)
H = LOOP // 2            # start of source bar 5
def cut(notes, a, b, shift):
    return [(t - a + shift, d, p, v) for (t, d, p, v) in notes if a <= t < b]
intro = {
    'lead': cut(lead, 6 * BAR, 8 * BAR, 2 * BAR),
    'comp': cut(comp, H + BAR, 8 * BAR, BAR),            # source bars 6-8 -> intro bars 2-4
    'bass': cut(bass, H, 8 * BAR, 0),
    'perc': cut(perc, H, 8 * BAR, 0),
}
song = {k: [(t + INTRO, d, p, v) for (t, d, p, v) in n] for k, n in
        (('lead', lead), ('comp', comp), ('bass', bass), ('perc', perc))}
full = {k: sorted(intro[k] + song[k]) for k in intro}

# ---- write the MIDI ----------------------------------------------------------------
def vlq(v):
    b = [v & 127]; v >>= 7
    while v: b.append((v & 127) | 128); v >>= 7
    return bytes(reversed(b))
def track(events):
    events.sort(key=lambda e: (e[0], e[1]))       # note-offs (order 0) before note-ons (order 1)
    out, last = b'', 0
    for t, _, data in events:
        out += vlq(t - last) + data; last = t
    out += vlq(0) + b'\xff\x2f\x00'
    return b'MTrk' + struct.pack('>I', len(out)) + out
def meta(t, ty, data): return (t, 0, bytes([0xFF, ty]) + vlq(len(data)) + data)
def notes_ev(ch, notes, prog=None):
    ev = []
    if prog is not None: ev.append((0, 0, bytes([0xC0 | ch, prog])))
    for t, d, p, v in notes:
        ev.append((t, 1, bytes([0x90 | ch, p, v]))); ev.append((t + d, 0, bytes([0x80 | ch, p, 0])))
    return ev
END = INTRO + LOOP
t0 = [meta(0, 3, b'D major bossa chiptune 84bpm (4-bar intro + 8-bar loop)'),
      meta(0, 0x51, bytes.fromhex('0ae62d')), meta(0, 0x58, bytes.fromhex('04021808')),
      meta(0, 0x59, bytes.fromhex('0200')),
      meta(0, 6, b'intro'), meta(INTRO, 6, b'loopStart'), meta(END, 6, b'loopEnd')]
tracks = [t0,
          [meta(0, 3, b'Lead P1 pulse 25%')] + notes_ev(0, full['lead'], 80),
          [meta(0, 3, b'Comp P2 pulse 12.5% (arp-strum)')] + notes_ev(1, full['comp'], 80),
          [meta(0, 3, b'Bass WAV')] + notes_ev(2, full['bass'], 38),
          [meta(0, 3, b'Noise perc (hat + side-stick clave)')] + notes_ev(9, full['perc'])]
data = b''.join(track(list(t)) for t in tracks)
open(OUT_MID, 'wb').write(b'MThd' + struct.pack('>IHHH', 6, 1, len(tracks), PPQ) + data)

# ---- GBA event table ---------------------------------------------------------------
# event: time (timer units), val (frequency register), ch (0 lead,1 comp,2 bass,3 noise), arg
def sq_rate(p): return int(round(2048 - 131072.0 / (440.0 * 2 ** ((p - 69) / 12.0))))
def wv_rate(p): return int(round(2048 - 65536.0 / (440.0 * 2 ** ((p - 69) / 12.0))))
ev = []
def vol(v, mul=1.0): return max(1, min(15, int(round(v / 127.0 * 15 * mul))))
def add(tick, ch, val, arg): ev.append((int(round(tick * UNITS_PER_TICK)), ch, val, arg))
def mono(ch, notes, rate, volf):
    for i, (t, d, p, v) in enumerate(notes):
        add(t, ch, rate(p), volf(v))
        nxt = notes[i + 1][0] if i + 1 < len(notes) else None
        if nxt is None or nxt - (t + d) > 3:      # skip the note-off when the next note follows at once
            add(t + d, ch, 0, 0)
mono(0, full['lead'], sq_rate, lambda v: vol(v, 1.15))
mono(1, full['comp'], sq_rate, lambda v: vol(v, 1.1))
mono(2, full['bass'], wv_rate, lambda v: 1)
for t, d, p, v in full['perc']:
    add(t, 3, 0, vol(v, 1.3) | ((1 if p == 42 else 2) << 4))
# order: by time; note-off before note-on at the same time
ev.sort(key=lambda e: (e[0], e[3] != 0 if e[1] < 3 else 1))
loop_idx = next(i for i, e in enumerate(ev) if e[0] >= INTRO * UNITS_PER_TICK - 0.5)
loop_units = int(round(LOOP * UNITS_PER_TICK))
with open('src/music_data.c', 'w') as o:
    o.write('// GENERATED by tools/make_music.py - do not edit\n#include "data.h"\n')
    o.write('const int MUSIC_COUNT = %d;\nconst int MUSIC_LOOP_IDX = %d;\nconst u32 MUSIC_LOOP_UNITS = %d;\n' % (len(ev), loop_idx, loop_units))
    o.write('const MusEv music_events[%d] = {\n' % len(ev))
    for i in range(0, len(ev), 4):
        o.write(' '.join('{%d,%d,%d,%d},' % (e[0], e[2], e[1], e[3]) for e in ev[i:i + 4]) + '\n')
    o.write('};\n')
print('events', len(ev), 'loop starts at event', loop_idx, 'loop units', loop_units,
      'intro sec %.2f  loop sec %.2f' % (INTRO / 960.0 * 60 / 84 * 2, LOOP / 960.0 * 60 / 84 * 2))
