"""Stitched painting -> GBA 8bpp scrolling background (src/bg_data.c).
Run:  python3 tools/make_bg.py      (needs Pillow, numpy, opencv-python)
"""
import numpy as np, cv2
from PIL import Image
W, H = 512, 448            # 64 x 56 tiles
NCOL = 224                 # palette 224..255 is reserved for the title text
im = cv2.imread('assets/painting_stitched.png')
im = cv2.resize(im, (W, H), interpolation=cv2.INTER_AREA)
f = im.astype(np.float32) / 255.0
f = np.power(f, 1.25) * 0.92                      # darker, so the title text pops
lab = cv2.cvtColor(f, cv2.COLOR_BGR2LAB)
lab[..., 0] = np.clip((lab[..., 0] - 50) * 1.12 + 47, 0, 100)   # a little contrast
f = np.clip(cv2.cvtColor(lab, cv2.COLOR_LAB2BGR), 0, 1)
rgb = (f[..., ::-1] * 255 + 0.5).astype(np.uint8)
rgb = (rgb >> 3) << 3                              # snap to GBA 5-bit colour
q = Image.fromarray(rgb).quantize(colors=NCOL, method=Image.Quantize.MEDIANCUT,
                                  dither=Image.Dither.FLOYDSTEINBERG)
idx = np.array(q, dtype=np.uint8)
pal = np.array(q.getpalette()[:NCOL * 3], dtype=np.uint8).reshape(-1, 3)
if len(pal) < NCOL: pal = np.vstack([pal, np.zeros((NCOL - len(pal), 3), np.uint8)])
pal15 = [(int(r) >> 3) | ((int(g) >> 3) << 5) | ((int(b) >> 3) << 10) for r, g, b in pal]
assert idx.max() < NCOL
tiles = idx.reshape(H // 8, 8, W // 8, 8).transpose(0, 2, 1, 3).reshape(-1, 64)
w = tiles.reshape(-1, 4).astype(np.uint32)
words = w[:, 0] | (w[:, 1] << 8) | (w[:, 2] << 16) | (w[:, 3] << 24)
with open('src/bg_data.c', 'w') as o:
    o.write('// GENERATED by tools/make_bg.py - do not edit\n#include "data.h"\n')
    o.write('const u16 bg_pal[%d] = {\n' % NCOL)
    o.write(',\n'.join(', '.join('0x%04x' % v for v in pal15[i:i + 16]) for i in range(0, NCOL, 16)) + '\n};\n')
    o.write('const u32 bg_tiles[%d] __attribute__((aligned(4))) = {\n' % len(words))
    for i in range(0, len(words), 8):
        o.write(', '.join('0x%08x' % int(v) for v in words[i:i + 8]) + ',\n')
    o.write('};\n')
Image.fromarray(np.array(q.convert('RGB'))).save('assets/bg_preview.png')
np.save('/tmp/bg_idx.npy', idx)
print('bg tiles', len(tiles), 'bytes', tiles.size)
